import sys
import subprocess
import os

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", package])

try:
    from pptx import Presentation
except ImportError:
    install('python-pptx')
    from pptx import Presentation

desktop_path = os.path.expanduser("~/Desktop/哥大与纽大_极简介绍.pptx")

prs = Presentation()

# Slide 1: Title
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "纽约双雄"
subtitle.text = "哥伦比亚大学 vs 纽约大学\n极其简约的学术之旅\n\nGenerated by 小可爱"

# Slide 2: 哥伦比亚大学 (Columbia University)
bullet_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(bullet_slide_layout)
title_shape = slide.shapes.title
body_shape = slide.placeholders[1]
title_shape.text = "哥伦比亚大学 (Columbia Univ.)"
tf = body_shape.text_frame
tf.text = "常春藤盟校，坐落于曼哈顿上西区晨边高地。"
p = tf.add_paragraph()
p.text = "古典校园：拥有纽约市区少见的传统封闭式校园，学术氛围庄重静谧。"
p = tf.add_paragraph()
p.text = "核心课程 (Core Curriculum)：本科教育的基石，培养广博的人文素养。"
p = tf.add_paragraph()
p.text = "王牌专业：新闻学（普利策奖诞生地）、法学、商学、国际关系等。"

# Slide 3: 纽约大学 (New York University)
slide = prs.slides.add_slide(bullet_slide_layout)
title_shape = slide.shapes.title
body_shape = slide.placeholders[1]
title_shape.text = "纽约大学 (NYU)"
tf = body_shape.text_frame
tf.text = "全美最大的私立大学之一，以格林威治村为绝对中心。"
p = tf.add_paragraph()
p.text = "没有围墙的大学：“整个纽约就是我们的校园”，与城市脉搏同频共振。"
p = tf.add_paragraph()
p.text = "创新与活力：极具艺术气息与商业头脑，实用主义至上。"
p = tf.add_paragraph()
p.text = "王牌学院：帝势艺术学院 (Tisch，电影人的摇篮)、斯特恩商学院 (Stern，直通华尔街)。"

# Slide 4: 风格对比与总结
slide = prs.slides.add_slide(bullet_slide_layout)
title_shape = slide.shapes.title
body_shape = slide.placeholders[1]
title_shape.text = "极简对比"
tf = body_shape.text_frame
tf.text = "选哥大还是纽大？"
p = tf.add_paragraph()
p.text = "哥伦比亚大学："
p = tf.add_paragraph()
p.text = "适合追求浓厚学术底蕴、喜欢传统校园生活、热爱经典人文思辨的“老灵魂”。"
p.level = 1
p = tf.add_paragraph()
p.text = "纽约大学："
p = tf.add_paragraph()
p.text = "适合热爱大都市喧嚣、渴望提前接触行业资源、充满创造力与活力的“实干家”。"
p.level = 1

prs.save(desktop_path)
print(f"PPT successfully created at: {desktop_path}")
